[STREAMPIPES-251] Add stop/start command to CLI, modified restart command with force-create option

diff --git a/cli/bin/commands/restart b/cli/bin/commands/restart
--- a/cli/bin/commands/restart
+++ b/cli/bin/commands/restart
@@ -16,18 +16,16 @@
 set -e
 . "$STREAMPIPES_WORKDIR/bin/common"
 
+remove_container=false
+
 cli_help_restart() {
   cat <<EOF
-Restart StreamPipes environment or individual services
+Restart running StreamPipes containers
 
-Usage: streampipes restart [SERVICE...]
+Usage: streampipes restart [OPTIONS] [SERVICE...]
 
-Example:
-# Restart complete StreamPipes environment
-streampipes restart
-
-# Restart individual services in StreamPipes environment
-streampipes restart backend consul
+Options:
+  -f, --force-create   Remove container before restarting
 EOF
 
   exit 1
@@ -35,21 +33,45 @@ EOF
 
 [ "$1" == '--help' ] || [ "$1" == '-h' ] && cli_help_restart
 
-if is_streampipes_running; then
+if [ -z "$1" ]; then
+    fatal "Argument missing, see 'streampipes ${0##*/} --help'"
+fi
 
-  if [ -z "$1" ]; then
-    get_curr_environment
+while [[ "$#" -gt 0 ]]; do
+    case $1 in
+        -f|--force-create) 
+          if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+            remove_container=true
+            svc=$2
+            shift 2
+          else
+            fatal "Argument for $1 is missing" >&2
+          fi
+          ;;
+        -*|--*=) fatal "Unsupported flag $1, see 'streampipes ${0##*/} --help'" >&2 ;;
+        *) svc+=("$1"); shift ;;
+    esac
+done
+
+remove_and_restart() {
+    info "Removing and restarting ${svc[*]}"
     concatenate_compose_files
-    info "Restarting all services in environment: '$curr_environment'"
-    run "$docker_compose_files restart"
-  else
-    for svc in "$@"
-    do
-      info "Restarting $svc"
-      concatenate_compose_files
-      run "$docker_compose_files restart $svc"
-    done
-  fi
+    run "$docker_compose_files rm --stop -f ${svc[*]}"
+    run "$docker_compose_files up -d ${svc[*]}"
+}
+
+restart() {
+    info "Restarting ${svc[*]}"
+    concatenate_compose_files
+    run "$docker_compose_files restart ${svc[*]}"  
+}
+
+if is_streampipes_running; then
+    if [ "$remove_container" = true ]; then
+      remove_and_restart
+    else
+      restart
+    fi
 else
   info "No StreamPipes environment running"
 fi
diff --git a/cli/bin/commands/stop b/cli/bin/commands/stop
--- a/cli/bin/commands/stop
+++ b/cli/bin/commands/stop
@@ -16,47 +16,33 @@
 set -e
 . "$STREAMPIPES_WORKDIR/bin/common"
 
-list_stopped_containers=false
+cli_help_stop() {
+  cat <<EOF
+Stop individual StreamPipes containers
 
-cli_help_ps() {
-  cat << EOF
-List all StreamPipes containers
-
-Usage: streampipes ps [OPTIONS]
-
-Options:
-  -a, --all    Show all stopped containers
+Usage: streampipes stop [SERVICE...]
 EOF
 
   exit 1
 }
 
-[ "$1" == '--help' ] || [ "$1" == '-h' ] && cli_help_ps
+[ "$1" == '--help' ] || [ "$1" == '-h' ] && cli_help_stop
 
-if [ "$#" -gt 2 ]; then
-    fatal "Illegal number of arguments, see 'streampipes ${0##*/} --help'"
+if [ -z "$1" ]; then
+    fatal "Argument missing, see 'streampipes ${0##*/} --help'"
 fi
 
 while [[ "$#" -gt 0 ]]; do
     case $1 in
-        -a|--all) list_stopped_containers=true; shift ;;
-        -|--*=) fatal "Unsupported flag $1, see 'streampipes ${0##*/} --help'" >&2 ; shift ;;
-        *) fatal "Wrong usage, see 'streampipes ${0##*/} --help'" ;;
+        -*|--*=) fatal "Unsupported flag $1, see 'streampipes ${0##*/} --help'" >&2 ;;
+        *) svc+=("$1"); shift ;;
     esac
 done
 
 if is_streampipes_running; then
-  project_name=$(sed -n 's/^COMPOSE_PROJECT_NAME=//p' $STREAMPIPES_WORKDIR/.env)
-  if [ "$list_stopped_containers" = true ]; then
-    docker ps \
-        --filter "name=${project_name}_*" \
-        --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}' \
-        --all
-  else
-    docker ps \
-      --filter "name=${project_name}_*" \
-      --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}'
-  fi
+    info "Stopping ${svc[*]}"
+    concatenate_compose_files
+    run "$docker_compose_files stop ${svc[*]}"
 else
   info "No StreamPipes environment running"
 fi
