[STREAMPIPES-196] add option to inspect templates

diff --git a/cli/bin/commands/template b/cli/bin/commands/template
--- a/cli/bin/commands/template
+++ b/cli/bin/commands/template
@@ -16,6 +16,8 @@
 set -e
 . "$STREAMPIPES_WORKDIR/bin/common"
 
+STREAMPIPES_TEMPLATE_PATH=$STREAMPIPES_WORKDIR/bin/templates/environments
+
 cli_help_template() {
   cat <<EOF
 Select StreamPipes environment template
@@ -26,12 +28,16 @@ Example:
 # list all available environment templates
 streampipes template --list
 
+# inspect services in environment template
+streampipes template --inspect backend
+
 # set specific template, here 'backend'
 streampipes template --set backend
 
 Options:
-  -l, --list     List all available environment templates
-  -s, --set      Set environment templates
+  -i, --inspect   Inspect services in environment template
+  -l, --list      List all available environment templates
+  -s, --set       Set environment templates
 EOF
 
   exit 1
@@ -45,6 +51,14 @@ fi
 
 while [[ "$#" -gt 0 ]]; do
     case $1 in
+        -i|--inspect)
+          if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+            inspect_template="$2"
+            shift 2
+          else
+            fatal "Template for $1 is missing" >&2
+          fi
+          ;;
         -l|--list) list_templates=true; shift ;;
         -s|--set)
           if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
@@ -58,20 +72,48 @@ while [[ "$#" -gt 0 ]]; do
     esac
 done
 
-if [ "$list_templates" = true ]; then
-  info "Currently available StreamPipes environment templates"
-  for entry in "$STREAMPIPES_WORKDIR/bin/templates/environments"/*
+check_template(){
+  template=$STREAMPIPES_TEMPLATE_PATH/$1
+  if [ ! -f "$template" ]; then
+    fatal "Template not found '$1'. see 'streampipes ${0##*/} --list'"
+  fi
+}
+
+list_templates(){
+  info "StreamPipes environment templates"
+  for entry in "$STREAMPIPES_TEMPLATE_PATH"/*
   do
     echo "${entry##*/}"
   done
+}
+
+set_template(){
+  check_template $set_template
+  info "Set environment to template '$set_template'"
+  cp $STREAMPIPES_TEMPLATE_PATH/$set_template $STREAMPIPES_WORKDIR/.environment
+  set_lf_line_encoding $STREAMPIPES_WORKDIR/.environment
+}
+
+inspect_template(){
+  check_template $inspect_template
+  search_str="[environment:"
+
+  info "Inspect services in template '$inspect_template'"
+  while IFS='' read -r line || [[ -n "$line" ]]; do
+    if [[ "$line" != *"$search_str"* ]]; then
+      echo $line
+    fi
+  done < "$STREAMPIPES_TEMPLATE_PATH/$inspect_template"
+}
+
+if [ "$list_templates" = true ]; then
+  list_templates
+fi
+
+if [ -n "$inspect_template" ]; then
+  inspect_template
 fi
 
 if [ -n "$set_template" ]; then
-  if [ -e $STREAMPIPES_WORKDIR/bin/templates/environments/$set_template ]; then
-    info "Set environment template to '$set_template'"
-  	cp $STREAMPIPES_WORKDIR/bin/templates/environments/$set_template $STREAMPIPES_WORKDIR/.environment
-    set_lf_line_encoding $STREAMPIPES_WORKDIR/.environment
-  else
-  	fatal "Template not found '$set_template'"
-  fi
+  set_template
 fi
